# Licensed under the MIT License
# https://github.com/craigahobbs/bare-script-py/blob/main/LICENSE


# Download python-build
PYTHON_BUILD_DIR ?= ../python-build
define WGET
ifeq '$$(wildcard $(notdir $(1)))' ''
$$(info Downloading $(notdir $(1)))
$$(shell [ -f $(PYTHON_BUILD_DIR)/$(notdir $(1)) ] && cp $(PYTHON_BUILD_DIR)/$(notdir $(1)) . || $(call WGET_CMD, $(1)))
endif
endef
WGET_CMD = if command -v wget >/dev/null 2>&1; then wget -q -c $(1); else curl -f -Os $(1); fi
$(eval $(call WGET, https://craigahobbs.github.io/python-build/Makefile.base))
$(eval $(call WGET, https://craigahobbs.github.io/python-build/pylintrc))


# Sphinx documentation directory
SPHINX_DOC := doc


# Development dependencies
TESTS_REQUIRE := schema-markdown


# Use Python runtime, unless BARESCRIPT_RUNTIME_C is set
ifeq '$(BARESCRIPT_RUNTIME_C)' ''
export BARESCRIPT_RUNTIME_PY=1
DOCKER_ENV := -e BARESCRIPT_RUNTIME_PY=1
else
unexport BARESCRIPT_RUNTIME_PY
endif


# Include python-build
include Makefile.base


help:
	@echo "            [perf|runtime-c|sync|test-include]"


clean:
	rm -rf Makefile.base pylintrc src/bare_script/*.so


# Re-verify with the C runtime - a prerequisite rather than a commit recipe so it runs in parallel with the
# Python-runtime gate under "make -j"; the explicit prerequisites keep the sub-make from racing the outer
# make on venv creation and include-source generation
ifeq '$(BARESCRIPT_RUNTIME_C)' ''
.PHONY: commit-runtime-c
commit: commit-runtime-c
commit-runtime-c: $(DEFAULT_VENV_BUILD) src/bare_script/include_source.py
	$(MAKE) test test-include BARESCRIPT_RUNTIME_C=1
endif


.PHONY: sync
sync:
	cp SKILL.md ../bare-script/
	rsync -rv --delete --exclude=.git/ --exclude=__pycache__ src/bare_script/include/ ../bare-script/lib/include/
	rsync -rv --delete --exclude=.git/ static/ ../bare-script/static/


# Generate the include library source module
$(foreach IMAGE, $(PYTHON_IMAGES), $(eval test-$(call IMAGE_NAME_FN, $(IMAGE)): src/bare_script/include_source.py))
cover-$(call IMAGE_NAME_FN, $(firstword $(PYTHON_IMAGES))): src/bare_script/include_source.py
lint-$(call IMAGE_NAME_FN, $(firstword $(PYTHON_IMAGES))): src/bare_script/include_source.py
doc-$(call IMAGE_NAME_FN, $(firstword $(PYTHON_IMAGES))): src/bare_script/include_source.py
test-include-lint test-include-markdownup test-include-run perf: src/bare_script/include_source.py
src/bare_script/include_source.py: Makefile $(sort $(wildcard src/bare_script/include/*.bare)) | $(DEFAULT_VENV_BUILD)
	$(DEFAULT_VENV_PYTHON) -c "$$INCLUDE_SOURCE_PY" $@ $(filter %.bare,$^)


# Python to generate the include library source module
define INCLUDE_SOURCE_PY
import base64
import gzip
import json
import os
import re
import sys

from bare_script import barescript_parse_script

# Command-line arguments
_, output_path, *include_paths = sys.argv

# Generate the include library source module
parts = ['''\
# Licensed under the MIT License
# https://github.com/craigahobbs/bare-script-py/blob/main/LICENSE
# pylint: disable=line-too-long,missing-function-docstring,too-many-lines,useless-suppression

"""
This file is generated by "make src/bare_script/include_source.py" - do not edit
"""

import base64
import gzip


# Decode the map of include file name to gzip-compressed, base64-encoded include script model JSON
def _include_source_decode(encoded_includes):
    return {include_name: gzip.decompress(base64.b64decode(encoded)).decode('utf-8') for include_name, encoded in encoded_includes.items()}


# The map of system include file name to include script model JSON
SYSTEM_INCLUDES = _include_source_decode({
''']
includes = []
for include_path in include_paths:
    include_name = os.path.basename(include_path)[:-len('.bare')]
    with open(include_path, 'r', encoding='utf-8') as fh:
        include_text = fh.read()
    # Each include is embedded as its parser-compiled JSON script model ("scriptLines" omitted - it's unused
    # at runtime for system includes), gzip-compressed, base64-encoded, and chunked into 120-character string
    # lines, decoded at module load - the runtimes JSON-parse any system include starting with "{"
    model = barescript_parse_script(include_text, 1, f'{include_name}.bare')
    del model['scriptLines']
    model_text = json.dumps(model, separators=(',', ':'))
    model_encoded = base64.b64encode(gzip.compress(model_text.encode('utf-8'), compresslevel=9, mtime=0)).decode('ascii')
    model_lines_text = ',\n'.join(f"        '{chunk}'" for chunk in re.findall('.{1,120}', model_encoded))
    includes.append(f"    '{include_name}.bare': ''.join([\n{model_lines_text}\n    ])")
parts.append(',\n'.join(includes) + '\n})\n')
with open(output_path, 'w', encoding='utf-8') as fh:
    fh.write(''.join(parts))
endef
export INCLUDE_SOURCE_PY


# The include-test sub-targets are independent so they run in parallel under "make -j"
.PHONY: test-include test-include-lint test-include-markdownup test-include-run
commit: test-include
test-include: test-include-lint test-include-markdownup test-include-run
test-include-lint test-include-markdownup test-include-run: $(DEFAULT_VENV_BUILD)
test-include-lint:
	$(DEFAULT_VENV_BIN)/bare -x -m src/bare_script/include/*.bare src/bare_script/include/test/test*.bare
	$(DEFAULT_VENV_BIN)/bare -s -m src/bare_script/include/test/runTests.bare src/bare_script/include/test/runTestsMarkdownUp.bare
test-include-markdownup:
	$(DEFAULT_VENV_BIN)/bare -d -v vUnittestReport true src/bare_script/include/test/runTestsMarkdownUp.bare$(if $(TEST), -v vUnittestTest "'$(TEST)'")
test-include-run:
	$(DEFAULT_VENV_BIN)/bare -d -m src/bare_script/include/test/runTests.bare$(if $(TEST), -v vUnittestTest "'$(TEST)'")


doc:
    # Copy statics
	cp -R static/* build/doc/html/

    # Generate the builtin library documentation
	$(DEFAULT_VENV_BIN)/bare -m \
		-v 'vFiles' "'$$($(DEFAULT_VENV_PYTHON) -c 'import json; import sys; print(json.dumps(sys.argv[1:]))' src/bare_script/library.py)'" \
		-v 'vOutput' "'build/doc/html/library/library-builtin.json'" \
		-c 'include <baredocCLI.bare>' \
		-c 'return baredocCLIMain()'

    # Generate the include library documentation
	$(DEFAULT_VENV_BIN)/bare -m \
		-v 'vFiles' "'$$($(DEFAULT_VENV_PYTHON) -c 'import json; import sys; print(json.dumps(sys.argv[1:]))' src/bare_script/include/*.bare)'" \
		-v 'vOutput' "'build/doc/html/library/library-include.json'" \
		-c 'include <baredocCLI.bare>' \
		-c 'return baredocCLIMain()'

     # Generate the single-page library documentation
	cd build/doc/html/library/ && \
	$(call DEFAULT_VENV_BIN_EX,../../../../)/bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <baredoc.bare>' \
		-c "baredocMain('library.json')" \
		> barescript-library.md

    # Generate the expression library documentation
	$(DEFAULT_VENV_PYTHON) -c "$$DOC_EXPR_PY" build/doc/html/library/library-builtin.json build/doc/html/library/expression-builtin.json

     # Generate the single-page expression library documentation
	cd build/doc/html/library/ && \
	$(call DEFAULT_VENV_BIN_EX,../../../../)/bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <baredoc.bare>' \
		-c "baredocMain('expression.json')" \
		> barescript-expression-library.md

    # Generate the library model documentation
	$(DEFAULT_VENV_PYTHON) -c "$$DOC_LIBRARY_MODEL_PY" build/doc/html/library/model.json

    # Generate the single-page library model documentation
	cd build/doc/html/library/ && \
	$(call DEFAULT_VENV_BIN_EX,../../../../)/bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <schemaDoc.bare>' \
		-c "schemaDocMain('model.json', 'The BareScript Library Models')" \
		> barescript-library-model.md

    # Generate the runtime model documentation
	$(DEFAULT_VENV_PYTHON) -c "$$DOC_RUNTIME_MODEL_PY" build/doc/html/model/model.json

    # Generate the single-page runtime model documentation
	cd build/doc/html/model/ && \
	$(call DEFAULT_VENV_BIN_EX,../../../../)/bare -m \
		-v 'vSingle' 'true' \
		-v 'vPublish' 'true' \
		-c 'include <schemaDoc.bare>' \
		-c "schemaDocMain('model.json', 'The BareScript Runtime Model')" \
		> barescript-model.md

    # Publish the AI assistant skill (llms.txt is copied from static/)
	cp SKILL.md build/doc/html/


# Python to generate the expression library documentation
define DOC_EXPR_PY
import json
import sys
from bare_script.library import EXPRESSION_FUNCTION_MAP
from bare_script.value import value_json

# Command-line arguments
_, library_path, expression_path = sys.argv

# Read the script library documentation model
with open(library_path, 'r', encoding='utf-8') as fh:
    library = json.load(fh)

# Create the expression documentation model
library_map = dict((func['name'], func) for func in library['functions'])
library_expr = {'functions': [dict(library_map[lib_name], name=expr_name) for expr_name, lib_name in EXPRESSION_FUNCTION_MAP.items()]}

# Write the expression documentation model
with open(expression_path, 'w', encoding='utf-8') as fh:
    fh.write(value_json(library_expr))
endef
export DOC_EXPR_PY


# Python to generate the library type model
define DOC_LIBRARY_MODEL_PY
import sys
from bare_script import barescript_parse_script, execute_script, fetch_read_write, log_stdout
from bare_script.value import value_json

# Command-line arguments
_, type_model_path = sys.argv

# Create the include library type model
script = barescript_parse_script('''\
include 'src/bare_script/include/args.bare'
include 'src/bare_script/include/baredoc.bare'
include 'src/bare_script/include/data.bare'
include 'src/bare_script/include/dataLineChart.bare'
include 'src/bare_script/include/dataTable.bare'
include 'src/bare_script/include/diff.bare'
include 'src/bare_script/include/markdown.bare'
include 'src/bare_script/include/markdownElements.bare'
include 'src/bare_script/include/markdownHighlight.bare'
include 'src/bare_script/include/pager.bare'

includeTypes = {}
objectAssign(includeTypes, argsTypes)
objectAssign(includeTypes, baredocTypes)
objectAssign(includeTypes, dataAggregationTypes)
objectAssign(includeTypes, dataLineChartTypes)
objectAssign(includeTypes, dataTableTypes)
objectAssign(includeTypes, diffTypes)
objectAssign(includeTypes, markdownElementsTypes)
objectAssign(includeTypes, markdownHighlightTypes)
objectAssign(includeTypes, markdownTypes)
objectAssign(includeTypes, pagerTypes)
return includeTypes
''')
types = execute_script(script, {'fetchFn': fetch_read_write, 'logFn': log_stdout})

# Write the library type model
with open(type_model_path, 'w', encoding='utf-8') as fh:
    fh.write(value_json(types))
endef
export DOC_LIBRARY_MODEL_PY


# Python to generate the runtime type model
define DOC_RUNTIME_MODEL_PY
import sys
from bare_script.include import barescript_type_model
from bare_script.value import value_json

# Command-line arguments
_, type_model_path = sys.argv

# Write the runtime type model
with open(type_model_path, 'w', encoding='utf-8') as fh:
    fh.write(value_json(barescript_type_model()))
endef
export DOC_RUNTIME_MODEL_PY


# Performance test constants
PERF_BARE_JS_DIR := ../bare-script
PERF_CSV := build/perf.csv
PERF_CSV_TMP := build/perf-$$PPID.csv
PERF_MERGE := 1
PERF_REPORT := 1
PERF_RUNS := 2


# Run performance tests - write to a temporary CSV ($$PPID is the make process ID) and move it into
# place on success so build/perf.csv is always a complete, valid CSV
.PHONY: perf
perf: $(DEFAULT_VENV_BUILD)
	mkdir -p $(dir $(PERF_CSV_TMP))
	echo "language,test,runs,timeMs" > $(PERF_CSV_TMP)
	set -e; for X in $$(seq 1 $(PERF_RUNS)); do \
		echo "Run $$X of $(PERF_RUNS) - BareScript (PyC)"; \
		BARESCRIPT_RUNTIME_PY= $(DEFAULT_VENV_BIN)/bare perf/test.bare -v vLanguage "'BareScript (PyC)'"$(if $(TEST), -v vTest "'$(TEST)'") >> $(PERF_CSV_TMP); \
		echo "Run $$X of $(PERF_RUNS) - BareScript (Py)"; \
		BARESCRIPT_RUNTIME_PY=1 $(DEFAULT_VENV_BIN)/bare perf/test.bare -v vLanguage "'BareScript (Py)'"$(if $(TEST), -v vTest "'$(TEST)'") >> $(PERF_CSV_TMP); \
		echo "Run $$X of $(PERF_RUNS) - Python"; \
		$(DEFAULT_VENV_PYTHON) perf/test.py "Python"$(if $(TEST), "$(TEST)") >> $(PERF_CSV_TMP); \
	done
ifneq '$(PERF_MERGE)' ''
ifneq '$(wildcard $(PERF_BARE_JS_DIR))' ''
	$(MAKE) -C $(PERF_BARE_JS_DIR) perf PERF_RUNS=$(PERF_RUNS) TEST=$(TEST) PERF_MERGE= PERF_REPORT=
	tail -n +2 $(PERF_BARE_JS_DIR)/$(PERF_CSV) >> $(PERF_CSV_TMP)
endif
endif
	mv $(PERF_CSV_TMP) $(PERF_CSV)
ifneq '$(PERF_REPORT)' ''
	$(DEFAULT_VENV_PYTHON) -c "$$PERF_PY"
endif


# Python to report on performance test data
define PERF_PY
import csv

# Format a number with trailing zeros trimmed
def number_trim(value, digits):
    return f'{value:.{digits}f}'.rstrip('0').rstrip('.')

# Read the performance test data - compute the best per-run timing per test and language
test_timings = {}
with open('$(PERF_CSV)', 'r', encoding='utf-8') as fh:
    for row in csv.DictReader(fh):
        timings = test_timings.setdefault(row['test'], {})
        time_ms = float(row['timeMs']) / float(row['runs'])
        if row['language'] not in timings or time_ms < timings[row['language']]:
            timings[row['language']] = time_ms

# Compute the run multiplier - the smallest power of ten that reports every timing at or above one millisecond
run_multiplier = 1
min_timing = min((time_ms for timings in test_timings.values() for time_ms in timings.values()), default=0)
while min_timing > 0 and min_timing * run_multiplier < 1:
    run_multiplier *= 10

# Report the timing multiples for each test
per_runs = 'run' if run_multiplier == 1 else f'{run_multiplier} runs'
for ix_test, (test, timings) in enumerate(sorted(test_timings.items())):
    if ix_test != 0:
        print()
    best_timing = min(timings.values())
    print(f'{test}:')
    for language, time_ms in sorted(timings.items(), key=lambda val: val[1]):
        print(f'    {language} - {time_ms * run_multiplier:.1f} milliseconds per {per_runs} ({number_trim(time_ms / best_timing, 1)}x)')
endef
export PERF_PY


# Port runtime to C for performance
.PHONY: runtime-c
runtime-c:
	$(if $(OPTIMIZE_OLLAMA), ANTHROPIC_BASE_URL=http://localhost:11434 ANTHROPIC_AUTH_TOKEN=ollama ANTHROPIC_API_KEY="" )claude \
		--enable-auto-mode \
		--model $(if $(OPTIMIZE_MODEL),$(OPTIMIZE_MODEL),fable) \
		--effort $(if $(OPTIMIZE_EFFORT),$(OPTIMIZE_EFFORT),xhigh) \
		"$$(cat perf/claude-runtime-c.md)"
